Simple tip to avoid problems with data structures due to the broadcasting features in numpy/python

In [1]:
import numpy as np

a = np.random.randn(5) # rank 1 array

In [2]:
print(a)

[ 0.76042607 -0.84843412 -0.60582303  0.34536481 -1.50205693]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T) # bad!

[ 0.76042607 -0.84843412 -0.60582303  0.34536481 -1.50205693]


In [5]:
print(a @ a.T)

4.040561696482466


In [7]:
a = np.random.randn(5,1)
print(a)

[[ 1.52295826]
 [ 2.03937525]
 [ 1.08977057]
 [-0.0792763 ]
 [ 0.5705144 ]]


In [8]:
print(a.T)

[[ 1.52295826  2.03937525  1.08977057 -0.0792763   0.5705144 ]]


In [9]:
print(a @ a.T)

[[ 2.31940185  3.10588338  1.65967508 -0.12073449  0.86886962]
 [ 3.10588338  4.15905141  2.22245113 -0.16167411  1.16349295]
 [ 1.65967508  2.22245113  1.18759989 -0.08639297  0.6217298 ]
 [-0.12073449 -0.16167411 -0.08639297  0.00628473 -0.04522827]
 [ 0.86886962  1.16349295  0.6217298  -0.04522827  0.32548668]]
